name: frontend-project-lvl2
on: [push]
jobs:
  Linter:
    runs-on: ubuntu-latest
    steps:
      - run: make install
      - name: run eslint
        run: make lint
      - run: echo "ğŸ This job's status is ${{ job.status }}."
